### ISSUE TITLE
AppImage for download?

### ISSUE THREAD

**Issue by probonopd** [deep5050/qikQR#9]
Can you please provide the AppImage for download on GitHub Releases? Thanks.

**Comment by deep5050** [comment]
@probonopd I've updated the release with the same :)
Thanks for checking this repo. Feel free to suggest any features or submit bugs :)

**Comment by probonopd** [comment]
Is there a special reason why the architecture is missing in the AppImage filename?

**Comment by probonopd** [comment]
Thank you very much :+1:
